export const ModelCollections = {
	ACTIVITY_LOG: "activity_log",
	INSTRUCTOR: "instructor",
	STUDENT: "student",
	PARENT: "parent",
	CHAPTER: "chapter",
	SECTION: "section",
	QUESTION: "question",
	ANSWER: "answer",
	COMMENT: "comment",
	RATING: "rating",
	REVIEW: "review",
	NOTIFICATION: "notification",
	MESSAGE: "message",
	COMMUNITY_MESSAGE: "community_message",
	LOCATION: "location",

	PARENT_STUDENT_LINK: "parent_student_link",

	COMMUNITY: "community",
	COMMUNITY_MEMBER: "community_member",
	COMMUNITY_POST: "community_post",
	COURSE: "course",
	MODULE: "module",
	LESSON: "lesson",

	ASSIGNMENT: "assignment",
	ASSIGNMENT_SUBMISSION: "assignment_submission",
	QUIZ: "quiz",
	QUIZ_ATTEMPT: "quiz_attempt",

	ENROLLMENT: "enrollment",
	LEARNING_STREAK: "learning_streak",
	LESSON_PROGRESS: "lesson_progress",
	CERTIFICATE: "certificate",
	SUBSCRIPTION: "subscription",
	PAYMENT: "payment",
	WITHDRAWAL: "withdrawal",
	TEACHER_BALANCE: "teacher_balance",
	REFERRAL: "referral",
	LIVE_ATTENDANCE: "live_attendance",
};
